<?php

namespace AppBundle\Repository;

/**
 * BookCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
