<?php

namespace AppBundle\Repository;

/**
 * LendingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LendingRepository extends \Doctrine\ORM\EntityRepository
{
}
